### ISSUE TITLE
RunUseCase.py doesn't work for users with current instructions

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1026]
I just tried testing the deployments for all three platforms, following the instructions given.  The python use cases won't run. Each one fails with:

```
ModuleNotFoundError: No module named 'shapeworks'
```

Should we add this to the top of RunUseCase.py?

```
import setupenv
setupenv.setup_shapeworks_env()
```

**Comment by iyerkrithika21** [comment]
Adding `setupenv.setup_shapeworks_env()` could work because most of the times, this error goes away when `ShapeWorks/build/bin/` is added to the `PYTHONPATH`

**Comment by akenmorris** [comment]
I believe I've fixed it for all platforms.  Ok to merge?

**Comment by jadie1** [comment]
Reflection was still not working when femurs are groomed with meshes. @archanasri we need the shapeworks.cpp change

**Comment by archanasri** [comment]
@jadie1 what change are we talking about?

**Comment by jadie1** [comment]
Sorry ignore that, wrong issue, got mixed up.

**Comment by sheryjoe** [comment]
Where are we on this issue?

**Comment by archanasri** [comment]
The fix has been merged to the release branch.
