### ISSUE TITLE
add shapeworks namespace

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#162]
```
namespace shapeworks 
{
...
}
```

**Comment by sheryjoe** [comment]
@cchriste this might have been already addressed.

**Comment by cchriste** [comment]
Lots of stuff still not in shapeworks namespace. See #431 for example

**Comment by cchriste** [comment]
Stuff that needs to be added to the shapeworks namespace can get its own issue. Closing this.
